r_binary_packages:  
  - rmarkdown
  - knitr
  - matrixStats
  - RCurl
  - bitops
  - DBI
  - RSQLite
  - bit64
  - blob
  - memoise
  - pkgconfig
  - BH
  - plogr
  - bit
  - rlang
  - vctrs
  - digest
  - ellipsis
  - glue
  - XML
  - progress
  - stringr
  - httr
  - openssl
  - rappdirs
  - crayon
  - dbplyr
  - dplyr
  - curl
  - jsonlite
  - mime
  - R6
  - askpass
  - hms
  - prettyunits
  - magrittr
  - stringi
  - sys
  - futile.logger
  - snow
  - assertthat
  - lifecycle
  - purrr
  - tibble
  - tidyselect
  - lambda.r
  - futile.options
  - cli
  - fansi
  - pillar
  - formatR
  - utf8
  - lazyeval
  - yaml
  - shiny
  - httpuv
  - xtable
  - htmltools
  - sourcetools
  - later
  - promises
  - fastmap
  - ggplot2
  - reshape2
  - gtable
  - isoband
  - scales
  - withr
  - plyr
  - testthat
  - farver
  - labeling
  - munsell
  - RColorBrewer
  - viridisLite
  - colorspace
  - evaluate
  - pkgload
  - praise
  - desc
  - pkgbuild
  - rprojroot
  - rstudioapi
  - callr
  - backports
  - processx
  - ps
  - ggbeeswarm
  - viridis
  - irlba
  - rsvd
  - beeswarm
  - vipor
  - locfit
  - sitmo
  - globals
  - listenv
  - future
  - reticulate
  - igraph
  - zoo
  - base64enc
  - htmlwidgets
  - tidyr
  - hexbin
  - crosstalk
  - data.table
  - gplots
  - gtools
  - gdata
  - caTools
  - future.apply
  - FNN
  - RSpectra
  - dqrng
  - xfun
  - highr
  - markdown
  - abind
  - svMisc
  - statmod
  - ape
  - cowplot
  - fitdistrplus
  - ggrepel
  - ggridges
  - ica
  - leiden
  - lmtest
  - patchwork
  - pbapply
  - plotly
  - png
  - RANN
  - ROCR
  - Rtsne
  - sctransform
  - tsne
  - uwot
  - tinytex  
  - Rcpp
  - RcppAnnoy
  - RcppHNSW
  - RcppEigen
  - RcppProgress
language: r
sudo: false
os:
  - linux
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index
